apiVersion: v1
kind: Service
metadata:
  name: my-app-2
  labels:
    app: my-app-2
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    targetPort: http

  # Note here that we match both the app and the version
  selector:
    app: my-app-2
    version: v2.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-v2
  labels:
    app: my-app-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-2
      version: v2.0.0
  template:
    metadata:
      labels:
        app: my-app-2
        version: v2.0.0
    spec:
      containers:
      - name: my-app-2
        image: deekshithsn/k8s-deployment-strategies
        ports:
        - name: http
          containerPort: 5000
        - name: probe
          containerPort: 5000
        env:
        - name: VERSION
          value: v2.0.0
        livenessProbe:
          httpGet:
            path: /live
            port: probe
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: probe
          periodSeconds: 5