apiVersion: apps/v1
kind: Deployment
metadata:
    name: example
spec:
    selector:
        matchLabels:
            app: example
            version: v1.0.0
    replicas: 2
    template:
        metadata:
            labels:
                app: example
                version: v1.0.0
        spec:
            containers:
                - name: example-api
                  imagePullPolicy: Never
                  image: dipak:latest
                  resources:
                      limits:
                          cpu: 50m
                          memory: 100Mi
                      requests:
                          cpu: 25m
                          memory: 10Mi
                  ports:
                      - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: example
spec:
    selector:
        app: example
        version: v1.0.0
    ports:
        - port: 5000
          targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
    - host: dipakparmar.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: example
                port:
                  number: 5000
          - path: /v2
            pathType: Prefix
            backend:
              service:
                name: example-2
                port:
                  number: 5000

---


apiVersion: apps/v1
kind: Deployment
metadata:
    name: example-2
spec:
    selector:
        matchLabels:
            app: example-2
            version: v2.0.0
    replicas: 2
    template:
        metadata:
            labels:
                app: example-2
                version: v2.0.0
        spec:
            containers:
                - name: example-api-2
                  imagePullPolicy: Never
                  image: deekshithsn/k8s-deployment-strategies
                  resources:
                      limits:
                          cpu: 50m
                          memory: 100Mi
                      requests:
                          cpu: 25m
                          memory: 10Mi
                  ports:
                      - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: example-2
spec:
    selector:
        app: example-2
        version: v2.0.0
    ports:
        - port: 5000
          targetPort: 5000
---